### ISSUE TITLE
Notebook started with jupyterhub doesn't list iTorch kernel

### ISSUE THREAD

**Issue by simopal6** [facebook/iTorch#101]
On a docker Ubuntu 14.04 machine (the default "ubuntu" image), I installed jupyterhub, following the instructions in https://github.com/jupyter/jupyterhub, then I installed Torch7 using the standard procedure (install-deps.sh and install.sh).

If I run `jupyter notebook`, I can create a new iTorch notebook (i.e. the corresponding option appears under the "New" menu).

If I run `jupyterhub` and log in, the iTorch option for creating a new notebook is missing.

**Comment by simopal6** [comment]
The installation I referred to had been performed in user `root`'s home directory, and I was logging in on jupyterhub with user `testuser`.

After installing Torch and iTorch also in `testuser`'s home directory, the iTorch option appears. I don't know how jupyter works, but I guess it's more its responsibility than iTorch's, so this issue can probably be closed.

**Comment by soumith** [comment]
Yea, so itorch (and usually custom kernels) are installed in ~/.ipython, so they are user-specific.
