### ISSUE TITLE
Cannot pass filepath to itorch.image

### ISSUE THREAD

**Issue by musically-ut** [facebook/iTorch#104]
It seems that `torch.typename` returns `nil` for `string`, as [documented](https://github.com/torch/torch7/blob/master/doc/utility.md#torch.typename), where as `torch.type` seems to return the correct type:

```
th> torch.type('string')
string
```

This makes `itorch.image` to fail when passed a file path.

```
.../torch/install/share/lua/5.1/itorch/gfx.lua:49: unhandled type in itorch.image:string
stack traceback:
	[C]: in function 'error'
	.../torch/install/share/lua/5.1/itorch/gfx.lua:49: in function 'f'
	[string "local f = function() return itorch.image(imgF..."]:1: in main chunk
        ...
```

So, I think [itorch.image](https://github.com/facebook/iTorch/blob/eb052fb2e9b641564dd68b1e27f64af4f593f128/gfx.lua#L14) should use `torch.type` instead of `torch.typename`.

**Comment by soumith** [comment]
Thanks for figuring out the bug. Fixed via https://github.com/facebook/iTorch/commit/4b2fb4a0d28cfa01c4753d54793c35b35e9611c0
