### ISSUE TITLE
No display on itorch.image()

### ISSUE THREAD

**Issue by Jigyasu** [facebook/iTorch#105]
I have recently installed itorch with
ipython 4.1.2
Python 3.5.1
openSUSE 13.2 (Harlequin)

Running the first example does not return an error but there is no display either
![screenshot from 2016-04-11 14 30 42](https://cloud.githubusercontent.com/assets/942921/14443129/2e4d8afc-fff2-11e5-97a2-0ee9adbf085d.png)

 I am able to save images and everything works fine if I used the notebook mode.

**Comment by soumith** [comment]
the images are only shown in an itorch notebook, not in the terminal.
