### ISSUE TITLE
luajit missing with TORCH_LUA_VERSION=52

### ISSUE THREAD

**Issue by Kaixhin** [facebook/iTorch#107]
Since I've installed Torch with `TORCH_LUA_VERSION=52`, iTorch keeps on killing and trying to restart the kernel, resulting in the following error:

```sh
/home/ka709/torch/install/bin/itorch_launcher: line 24: /home/ka709/torch/install/bin/luajit: No such file or directory
/home/ka709/torch/install/bin/itorch_launcher: line 25: /home/ka709/torch/install/bin/luajit: No such file or directory
```

**Comment by soumith** [comment]
hmmm. I do fall back to "lua", if luajit cant be found.
https://github.com/facebook/iTorch/blob/master/itorch_launcher#L5-L10

Is your itorch out of date?

**Comment by Kaixhin** [comment]
Yep must be. Cleaned my Torch install and cloned the latest version of iTorch and it's working fine.

**Comment by tryerrorman** [comment]
@Kaixhin I have exactly the same problem as you. And I have cleaned my Torch and reinstall with "TORCH_LUA_VERSION=LUA52 ./install.sh" again. And the same problem occured again. Can you give me some detail advice.

**Comment by tryerrorman** [comment]
I have fixed it by directly changing the itorch_launcher to 
`LUA=$currdir/lua
# ls $LUA >/dev/null 2>&1
# if [ $? == 1 ]; then
#     LUA=$currdir/lua
# fi`

I find that the $LUA is null and I dont know why.

**Comment by tryerrorman** [comment]
I have fixed it by directly changing the itorch_launcher to
``LUA=$currdir/lua`
ls $LUA >/dev/null 2>&1
if [ $? == 1 ]; then
LUA=$currdir/lua
`fi``

I find that the $LUA is null and I dont know why.

**Comment by tryerrorman** [comment]
I have fixed it by directly changing the itorch_launcher to
`LUA=$currdir/lua

ls $LUA >/dev/null 2>&1

if [ $? == 1 ]; then

LUA=$currdir/lua

fi`

I find that the $LUA is null and I dont know why.

**Comment by Kaixhin** [comment]
@tryerrorman I literally cloned the Torch distro again rather than using `clean.sh`. Then cloned this repo after reinstalling Torch and did `luarocks make` to install iTorch.

**Comment by tryerrorman** [comment]
@Kaixhin Thank you.
