### ISSUE TITLE
Error: Could not satisfy dependency: image 

### ISSUE THREAD

**Issue by JulianHill** [facebook/iTorch#12]
When I use the command 
```
luarocks make
```
in the iTorch folder I get the Error:
```
Error: Could not satisfy dependency: image 
```
And when I try to install the dependency image manually it responds:
```
luarocks install image
Error: No results matching query were found.
```

Regards

**Comment by soumith** [comment]
@JulianHill are you using your own installation of luarocks and/or luajit? 
Giving the output of "which luarocks" will be helpful.

in short, apart from the luarocks server, we add our own server to luarocks' search path, which has some much needed packages:
https://github.com/torch/rocks

**Comment by JulianHill** [comment]
The problem seems to be Anaconda. 
http://stackoverflow.com/questions/23992612/torch7-mac-installation-error
When I renamed the Anaconda folder to something different, the script finished successfully.
After the installation I could set the name to Anaconda again.

**Comment by JulianHill** [comment]
The command
```
which luarocks
```
gave the output:
```
/Users/julian/torch/bin/luarocks
```
after I changed the name of the Anaconda folder to something else.
The problem seems to be Anaconda. It seems to overwrite some paths. Do you have a better installation guide about how to to install torch and iTorch in combination with Anaconda?

**Comment by JulianHill** [comment]
Ok I could manage to run it with Anaconda installed but had to specify
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
But now when I run itorch notebook and try to load the images from the example with
```
require 'image';
 itorch.image({image.lena(), image.lena(), image.lena()})
```
The console output says:
```
libpng warning: Application built with libpng-1.4.12 but running with 1.6.16
[write_png_file] png_create_write_struct failed
```
Do I have to downgrade the libpng version to use itorch?

Regards

**Comment by soumith** [comment]
@JulianHill interesting. anaconda seems to also be shipping with its own libpng, if i understand correctly. i would say this is what we do already with the default torch install as of yesterday:
```
1. before installing torch, scrub anaconda from PATH
2. install all torch packages except iTorch
3. Now, put back anaconda into PATH and install iTorch
```

If I understand this, what would fix it is to reinstall the "image" package with anaconda IN path.
So, with anacond in the path, and as is, reinstall:
```bash
luarocks install image
```

Hopefully that should fix it.

**Comment by JulianHill** [comment]
The problem is then that the new torch install script http://torch.ch/docs/getting-started.html#_ 
installs the libpng 1.6.16. I removed it from brew, and after I run the torch installer script the 1.6.16 version is back again in brew.

**Comment by soumith** [comment]
ok, then i suggest manually removing it from brew and reinstalling the image package. (luarocks install image).

**Comment by JulianHill** [comment]
If I remove it manually, the ```luarocks install image```command does not install the version 14 needed. This seems to be a problem with the torch install script or? This shouldn´t install the version 16 at all.

**Comment by soumith** [comment]
i dont understand.
Basically there's two parts to the torch install.
(1) installing dependencies. You have already done this once, so dont do it again. This is the part that installs libpng from brew.

(2) installing torch itself. You have also done this, but when you did this earlier, torch's image package linked against libpng 16. You say you want to link against libpng14 that you already have.
So, remove the homebrew libpng, and then just run "luarocks install image". that WILL NOT install libpng.

**Comment by antonheryanto** [comment]
got similar problem recently turn out the problem because CMake using Mono.Framework libpng, because its installed in /Library/Frameworks/Mono.Framework which CMake find its library. find out using 
```bash
$ locate libpng-config
/Library/Frameworks/Mono.framework/Versions/3.12.0/bin/libpng-config
/usr/X11/bin/libpng-config
/usr/local/Cellar/libpng/1.6.16/bin/libpng-config
/usr/local/bin/libpng-config
/usr/local/octave/3.8.2/bin/libpng-config
```
and execute libpng-config version and found match version 1.4.12 with mono version, move this Mono.Framework folder to other place and re install torch fix the problem

**Comment by cancan101** [comment]
I am having trouble installing `image` as well (on OS X 10.10):
```
$ luarocks install  --server=https://raw.githubusercontent.com/torch/rocks/master  image
Installing https://raw.githubusercontent.com/torch/rocks/master/image-1.1.alpha-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/image-1.1.alpha-0.rockspec... switching to 'build' mode

Missing dependencies for image:
sys >= 1.0
xlua >= 1.0

Using https://raw.githubusercontent.com/torch/rocks/master/sys-1.1-0.rockspec... switching to 'build' mode
Cloning into 'sys'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 9 (delta 1), reused 6 (delta 1), pack-reused 0
Receiving objects: 100% (9/9), done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
Note: checking out '1bf9056edeefacf4a7e2b87260efd29dae92992e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/bin/.." -DCMAKE_INSTALL_PREFIX="/usr/local/lib/luarocks/rocks-5.2/sys/1.1-0" && make
-- The C compiler identification is AppleClang 6.1.0.6020053
-- The CXX compiler identification is AppleClang 6.1.0.6020053
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_sys-1.1-0-5173/sys/build
Scanning dependencies of target sys
[ 50%] Building C object CMakeFiles/sys.dir/sys.c.o
/tmp/luarocks_sys-1.1-0-5173/sys/sys.c:48:39: error: array has incomplete element type 'const struct luaL_reg'
static const struct luaL_reg routines [] = {
                                      ^
/tmp/luarocks_sys-1.1-0-5173/sys/sys.c:48:21: note: forward declaration of 'struct luaL_reg'
static const struct luaL_reg routines [] = {
                    ^
/tmp/luarocks_sys-1.1-0-5173/sys/sys.c:56:3: warning: implicit declaration of function 'luaL_openlib' is invalid in C99 [-Wimplicit-function-declaration]
  luaL_openlib(L, "libsys", routines, 0);
  ^
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/sys.dir/sys.c.o] Error 1
make[1]: *** [CMakeFiles/sys.dir/all] Error 2
make: *** [all] Error 2

Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/sys-1.1-0.rockspec - Build error: Failed building.
```

**Comment by DSLituiev** [comment]
Is there any fix to this problem?
I have:
```which luarocks
/usr/local/bin/luarocks```

```
locate libpng-config
/Applications/_anaconda/bin/libpng-config
/Applications/_anaconda/pkgs/libpng-1.6.17-0/bin/libpng-config
/Applications/_anaconda2.7/anaconda/bin/libpng-config
/Library/Frameworks/UnixImageIO.framework/Versions/E/Programs/libpng-config
/_anaconda/bin/libpng-config
/_anaconda/pkgs/libpng-1.6.17-0/bin/libpng-config
/opt/X11/bin/libpng-config
/usr/local/Cellar/libpng/1.6.17/bin/libpng-config
/usr/local/Cellar/libpng/1.6.18/bin/libpng-config
/usr/local/Cellar/libpng/1.6.21/bin/libpng-config
/usr/local/bin/libpng-config
```

I tried to purge and reinstall `libpng` with `brew`, still getting the same problem with itorch.
