### ISSUE TITLE
[Ubuntu 16] Facing issues in starting the iTorch Kernel

### ISSUE THREAD

**Issue by Abdul--Muqeet** [facebook/iTorch#125]
Whenever, I start the iTorch Kernel,  it dies and shows the following the error. 

[I 04:17:34.860 NotebookApp] Kernel started: fdf63071-81e7-401e-ad6a-b5b343fcc3fb
/home/abdul/torch/install/bin/luajit: error loading module 'lzmq' from file '/home/abdul/torch/install/lib/lua/5.1/lzmq.so':
	libzmq.so.3: cannot open shared object file: No such file or directory
stack traceback:
	[C]: at 0x0047aff0
	[C]: in function 'require'
	/home/abdul/torch/install/share/lua/5.1/itorch/main.lua:11: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x00406670
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
/home/abdul/torch/install/bin/luajit: error loading module 'lzmq' from file '/home/abdul/torch/install/lib/lua/5.1/lzmq.so':
	libzmq.so.3: cannot open shared object file: No such file or directory
stack traceback:
	[C]: at 0x0047aff0
	[C]: in function 'require'
	...e/abdul/torch/install/share/lua/5.1/itorch/IOHandler.lua:12: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x00406670

**Comment by Abdul--Muqeet** [comment]
Again Installing the dependencies and torch has done the job. After the installation, I used `luarocks install lzmq` to install the 'lzmq' which was not working previously.

**Comment by veonua** [comment]
it cost me 3 hours of my life. reinstalling libraries. just for a record :disappointed:

**Comment by soumith** [comment]
@veonua is it the same error as above, or did you run into something else?

**Comment by veonua** [comment]
yes, unfortunately Google doesn't show this page on top. so I've tried to
reinstall libzmq using apt-get. solution here worked.

it would be very nice to put this solution somewhere in readme.

**Comment by soumith** [comment]
@veonua the Requirements part gives commands to install libzmq here: https://github.com/facebook/iTorch#requirements

If you think that's not enough, i can add more info into the readme.
Thanks for the feedback

**Comment by veonua** [comment]
https://github.com/facebook/iTorch/pull/133
