### ISSUE TITLE
problem with jupyter 4, OSX, Enthought Canopy

### ISSUE THREAD

**Issue by tesla9** [facebook/iTorch#130]
Hi,
The simplest way (I think) to instal jupyter and scientific python libraries on OS X is to do it using Canopy Enthought python distribution. Unfortunately after iTorch installation I have very similar problem to this one described here:
https://github.com/facebook/iTorch/issues/97
I am unable to downgrade jupyter to lower than 4 version using Canopy package manager. Is there any workaround to make iTorch working on OSX and jupyter 4. 
My log bellow:

jupyter notebook
[I 12:35:00.175 NotebookApp] Serving notebooks from local directory: /Users/JKPie
[I 12:35:00.175 NotebookApp] 0 active kernels 
[I 12:35:00.175 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 12:35:00.175 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 12:35:15.936 NotebookApp] Notebook libs/torch/iTorch/iTorch_Demo.ipynb is not trusted
[I 12:35:16.514 NotebookApp] Kernel started: e1e8b782-e6b0-4cae-a7f6-d6fde2f20508
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
	
[I 12:35:16.838 NotebookApp] Adapting to protocol v4.0 for kernel e1e8b782-e6b0-4cae-a7f6-d6fde2f20508
/Users/JKPie/libs/torch/install/bin/luajit: ...s/JKPie/libs/torch/install/share/lua/5.1/itorch/main.lua:350: Cannot find appropriate message handler for comm_info_request
stack traceback:
	[C]: in function 'assert'
	...s/JKPie/libs/torch/install/share/lua/5.1/itorch/main.lua:350: in function <...s/JKPie/libs/torch/install/share/lua/5.1/itorch/main.lua:348>
	...s/JKPie/libs/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	...KPie/libs/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	...KPie/libs/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	...KPie/libs/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	...s/JKPie/libs/torch/install/share/lua/5.1/itorch/main.lua:381: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x010972fd00
[I 12:35:29.933 NotebookApp] Saving file at /libs/torch/iTorch/iTorch_Demo.ipynb
[W 12:35:29.933 NotebookApp] Saving untrusted notebook libs/torch/iTorch/iTorch_Demo.ipynb

**Comment by DmitryUlyanov** [comment]
Experiencing the same issue on Ubuntu 14.04

```
[I 14:11:42.527 NotebookApp] Adapting to protocol v4.0 for kernel 8373872e-cb07-480f-9689-f89a882a6495
/home/dulyanov/torch/install/bin/luajit: /home/dulyanov/torch/install/share/lua/5.1/itorch/main.lua:350: Cannot find appropriate message handler for comm_info_request
stack traceback:
        [C]: in function 'assert'
        /home/dulyanov/torch/install/share/lua/5.1/itorch/main.lua:350: in function </home/dulyanov/torch/install/share/lua/5.1/itorch/main.lua:348>
        /home/dulyanov/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
        .../dulyanov/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
        .../dulyanov/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
        .../dulyanov/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
        /home/dulyanov/torch/install/share/lua/5.1/itorch/main.lua:381: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x00406670
```

**Comment by kirk86** [comment]
Same issue here. Every time I try to execute a cell I get the following error message.

```
Adapting to protocol v4.0 for kernel 37e4655a-7bff-4e56-8d61-48cc9faf275a
/Users/user/torch/install/bin/luajit: /Users/user/torch/install/share/lua/5.1/itorch/main.lua:350: Cannot find appropriate message handler for comm_info_request
stack traceback:
       	[C]: in function 'assert'
       	/Users/user/torch/install/share/lua/5.1/itorch/main.lua:350: in function </Users/user/torch/install/share/lua/5.1/itorch/main.lua:348>
       	/Users/user/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
       	/Users/user/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
       	/Users/user/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
       	/Users/user/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
       	/Users/user/torch/install/share/lua/5.1/itorch/main.lua:381: in main chunk
       	[C]: in function 'require'
       	(command line):1: in main chunk
       	[C]: at 0x010b1fa640
```

**Comment by soumith** [comment]
I'm looking into it now.

**Comment by kirk86** [comment]
ok thanks Soumith

**Comment by soumith** [comment]
fixed via https://github.com/facebook/iTorch/commit/321703e54dc7e8548bcf4ed9b93dfc402f668cd8

**Comment by ChrisGll** [comment]
Same issue here, on Ubuntu 14.04:

````
Adapting to protocol v4.0 for kernel 458e2f41-b0f6-4ff8-a4a0-ded44d61b7c5
/home/yann/torch/install/bin/luajit: /home/yann/torch/install/share/lua/5.1/itorch/main.lua:350: Cannot find appropriate message handler for comm_info_request
stack traceback:
	[C]: in function 'assert'
	/home/yann/torch/install/share/lua/5.1/itorch/main.lua:350: in function </home/yann/torch/install/share/lua/5.1/itorch/main.lua:348>
	/home/yann/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	/home/yann/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	/home/yann/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	/home/yann/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/home/yann/torch/install/share/lua/5.1/itorch/main.lua:381: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x00406670
````

I tried to fix it as you advised, but if I run `luarocks install itorch` in terminal, it gets denied:
````
$luarocks install itorch
Installing https://raw.githubusercontent.com/torch/rocks/master/itorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/itorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'iTorch'...
remote: Counting objects: 45, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 45 (delta 1), reused 25 (delta 0), pack-reused 0
Receiving objects: 100% (45/45), 5.18 MiB | 701.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
mkdir: cannot create directory ‘/home/yann/torch/install/lib/luarocks/rocks/itorch/scm-1/bin’: Permission denied

Error: failed making directory /home/yann/torch/install/lib/luarocks/rocks/itorch/scm-1/bin
````

Whereas `sudo luarocks install itorch` also fails and returns
````
Error: No results matching query were found.
````

Where am I supposed to run `luarocks install itorch` ?
