### ISSUE TITLE
Locally-installed iTorch looking in incorrect `package.path` and `package.cpath`

### ISSUE THREAD

**Issue by alimuldal** [facebook/iTorch#16]
I've recently installed Torch-7 and iTorch on a shared workstation. I installed the whole Torch-7 distro locally in `~/torch`, as per [the instructions here](http://torch.ch/docs/getting-started.html#_). However, there is also a past installation of torch living in `/usr/local/lib/lua/5.1`, which is still used by a colleague of mine.

If I start my (locally-installed) iTorch and try to import a package that happens to be installed globally as well as locally, iTorch tries to import the globally installed version first. In some cases this leads to errors, since the global packages may be built against a different version of CUDA:

```
In [1]: cutorch = require 'cutorch'
error loading module 'libcutorch' from file '/usr/local/lib/lua/5.1/libcutorch.so':
        libcudart.so.6.0: cannot open shared object file: No such file or directory
stack traceback:
        [C]: at 0x00479a40
        [C]: in function 'require'
        /usr/local/share/lua/5.1/cutorch/init.lua:2: in main chunk
        [C]: in function 'require'
        [string "cutorch = require 'cutorch'..."]:1: in main chunk
        [C]: in function 'xpcall'
        /home/alistair/torch/install/share/lua/5.1/itorch/main.lua:194: in function </home/alistair/torch/install/share/lua/5.1/itorch/main.lua:160>
        /home/alistair/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
        .../alistair/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
        .../alistair/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
        .../alistair/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
        /home/alistair/torch/install/share/lua/5.1/itorch/main.lua:374: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x00406170
```
I think this is because when I start Itorch, the `package.path` and `package.cpath` are configured to look in the system-wide directories first:
```
In [2]: package.path
Out[2]: 
/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/home/alistair/.luarocks/share/lua/5.1/?.lua;/home/alistair/.luarocks/share/lua/5.1/?/init.lua;./?.lua;/home/alistair/torch/install/share/luajit-2.1.0-alpha/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/home/alistair/torch/install/share/lua/5.1/?.lua;/home/alistair/torch/install/share/lua/5.1/?/init.lua

In [3]: package.cpath
Out[3]: 
/usr/local/lib/lua/5.1/?.so;/home/alistair/.luarocks/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/home/alistair/torch/install/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
```
I am definitely starting the locally-installed iTorch, rather than a system-wide one:

```
~$ which itorch
/home/alistair/torch/install/bin/itorch
```
This seems to be specific to iTorch, since I don't see the same behaviour with `th`:

```
th> cutorch = require 'cutorch'
                                                                      [0.1513s]
th> package.path
/home/alistair/.luarocks/share/lua/5.1/?.lua;/home/alistair/.luarocks/share/lua/5.1/?/init.lua;/home/alistair/torch/install/share/lua/5.1/?.lua;/home/alistair/torch/install/share/lua/5.1/?/init.lua;./?.lua;/home/alistair/torch/install/share/luajit-2.1.0-alpha/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua
                                                                      [0.0000s]
th> package.cpath
/home/alistair/.luarocks/lib/lua/5.1/?.so;/home/alistair/torch/install/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
                                                                      [0.0001s]
th> 
```

Is there some way to configure iTorch so that `package.path` and `package.cpath` are set correctly, and modules are imported from local directories by default?

**Comment by soumith** [comment]
do two things.

clean up your old torch install by running this script:
https://github.com/torch/ezinstall/blob/master/clean-old.sh

add CUDA to your LD_LIBRARY_PATH, i.e.
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

**Comment by alimuldal** [comment]
1. Is it strictly necessary to remove the old system-wide installation? As I said, it's a shared machine, and a colleague of mine still uses the system-wide version so I don't want to mess up his environment!

2. Yes, my `LD_LIBRARY_PATH` already contains `/usr/local/cuda/lib64` (I can successfully import cutorch using `th`).

**Comment by soumith** [comment]
in that case you manually have to change the package.cpath from the interpreter:
package.cpath = '/home/alistair/.luarocks/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/home/alistair/torch/install/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so'

Also, I suggest that you cleanup the global install and ask your colleague to install a local version. A global AND a local install will not play well together, and the iTorch and cwrap issue you saw might only be the start.

**Comment by alimuldal** [comment]
Unfortunately, manually setting `package.path` and `package.cpath` within a running iTorch session doesn't fix the import error. I will ask my colleague if he'd mind installing a local version of Torch instead.

Out of interest, how are `package.path` and `package.cpath` initialised when I start a new interpreter session?
