### ISSUE TITLE
Error when using torch.html() with newlines in the HTML

### ISSUE THREAD

**Issue by bshillingford** [facebook/iTorch#17]
### To reproduce
Open a notebook and type into a cell:
```
itorch.html('<b>hello</b>\n<i>world</i>')
```
It produces the error shown below.

The following works fine, however, with the `\n` removed:
```
itorch.html('<b>hello</b> <i>world</i>')
```

### Error message shown in cell
```
Javascript error adding output!
SyntaxError: Unexpected token ILLEGAL
See your browser Javascript console for more details.
```

**Comment by soumith** [comment]
itorch html has to be double-escaped. it's basically first a javascript string that then gets pushed into a div tag with $(id).html(str).

In your case itorch.html('<b>hello</b>\\n<i>world</i>') will work.

I can fix this in two ways. I can add a warning in the documentation of this subtlety, or I have to write a patch to escape the string manually before sending it to the browser.

**Comment by bshillingford** [comment]
Ah, thanks, that wasn't clear to me from a quick skim in the developer's console. Perhaps escaping the string within `itorch.html` gives the user the least surprises.

**Comment by soumith** [comment]
Thanks, that's a good call. Fixed now in trunk via commit https://github.com/facebook/iTorch/commit/b38bec0a61f81ddd86110b2aa21be1194cd9ba59
