### ISSUE TITLE
No plots in public setting

### ISSUE THREAD

**Issue by szagoruyko** [facebook/iTorch#25]
I modified standard itorch config using this http://ipython.org/ipython-doc/2/notebook/public_server.html
It runs well allowing access to a remote server through firefox or chrome (not safari because of websockets problem), which is really awesome.
The plots however do not show up. If I click Save As and export notebook as HTML - they do show up.
Tested on ubuntu-os x, os x-ubuntu and ubuntu-ubuntu. Also images work well and localhost is well, of course.
Any ideas if that could be fixed?

**Comment by soumith** [comment]
In that case you have to set the notebook to be "trusted notebook" from the menu bar

**Comment by szagoruyko** [comment]
didn't help

**Comment by szagoruyko** [comment]
oh it was blocked by browser, now it works. thanks!

**Comment by YigitDemirag** [comment]
Hey szagoruyko, how did you solve your problem?
