### ISSUE TITLE
Problems using iTorch from the very beginning

### ISSUE THREAD

**Issue by abria** [facebook/iTorch#29]
Hi all,

I am following the [Getting started with Torch](http://code.madbits.com/wiki/doku.php?id=tutorial_basics) tutorial but I am experiencing problems from the very beginning when using it with iTorch.

When I launch ```itorch```, whatever command I write (even the basic command ```require```), it complains about bad syntax. For instance:

```
[alessandro@localhost]$ itorch
Python 2.7.6 (default, Feb 20 2015, 17:19:50)
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

IPython profile: torch

In [1]: require 'image'
  File "<ipython-input-1-62061b945f94>", line 1
    require 'image'
                  ^
SyntaxError: invalid syntax
```

The same command works from ```th```. But when I try to display an image, I get a libjpeg error:

```
th> i=image.lena()
/usr/local/torch/share/lua/5.1/trepl/init.lua:319: /usr/local/torch/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libjpeg' from file '/usr/local/torch/lib/lua/5.1/libjpeg.so':
        /usr/local/torch/lib/lua/5.1/libjpeg.so: undefined symbol: jpeg_mem_src
warning: <libjpeg> could not be loaded (is it installed?)
```

This is strange, because I do have a working libjpeg and libpng:
```
Package libjpeg-turbo-devel-1.2.1-3.el6_5.x86_64 already installed and latest version
Package 2:libpng-devel-1.2.49-1.el6_2.x86_64 already installed and latest version
```

So neither ```th``` nor ```itorch``` are working as expected, despite they have been built w/o problems.

I am running on CentOS 6.4.

Thank you in advance for your helpfulness.

(I have been told to open an issue here, see [this link](https://github.com/torch/torch7/issues/162) for the original thread)

**Comment by soumith** [comment]
We do not support CentOS 6.4.
We try and test our packages on the platforms we support, and if anyone has issues on those platforms, we help them fix those issues.

Supporting CentOS is hard for several reasons, outdated packages being the number one issue.

As a recommendation for Centos 6, I would suggest installing python and ipython via anaconda, and then install itorch. afaik you should see no issues.

wrt your second error, though you have a working libjpeg and libpng, they are known to be outdated. I do use torch regularly on centos 6.4 and I've had no issues using it (including the image package).
Try upgrading your packages after installing the [EPEL](https://fedoraproject.org/wiki/EPEL) repo

**Comment by ajtulloch** [comment]
As an aside - for the first error, it looks like the profile setup has failed, because you're going into a Python shell (`SyntaxError: invalid syntax` is a Python error).
