### ISSUE TITLE
[CentOS6.4] iTorch notebook fails with mktemp error

### ISSUE THREAD

**Issue by adamist521** [facebook/iTorch#3]
I'm using torch7 on CentOS 6.4 with torch-distro from this [github-page](https://github.com/soumith/torch-distro).
The error seems to be due mktemp command.
Any possible solution for this??

```
...
2015-01-14 23:51:44.734 [NotebookApp] Kernel started: ff252b94-88d6-4c13-b39b-
8d6a5874e5fa
mktemp: too few X's in template `itorch.stdout'
rm: missing operand
詳しくは `rm --help' を実行して下さい.
mkfifo: missing operand
詳しくは `mkfifo --help' を実行して下さい.
mktemp: too few X's in template `itorch.PORTNUM'
/home/**********/torch-distro/install/bin/itorch_launcher: line 13: $IO_STDO: amb
iguous redirect
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
/home/**********/torch-distro/install/bin/luajit: cannot open <> in mode r
stack traceback:
        [C]: at 0x7f59c61f5ee0
        [C]: in function 'DiskFile'
        .../torch-distro/install/share/lua/5.1/itorch/IOHandler.lua:50: in mai
n chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x00405330
...
```

********* is my dir name.

**Comment by ajtulloch** [comment]
@adamist521, would you be able to retry running iTorch after https://github.com/facebook/iTorch/commit/93314c28339ebc68ebf78616e44f4a60358fcd3e? I think that should fix the issue you ran into.

**Comment by adamist521** [comment]
I tried it and the error have been removed.
But then I got next following error...

```
kernel died, restart ([y]/n)? y
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
/home/********/torch-distro/install/bin/luajit: [EADDRINUSE] Address already in use (98)
stack traceback:
        [C]: in function 'zassert'
        .../torch-distro/install/share/lua/5.1/itorch/IOHandler.lua:42: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x00405330
/home/*******/torch-distro/install/bin/luajit: [EADDRINUSE] Address already in use (98)
stack traceback:
        [C]: in function 'zassert'
        ...*****/torch-distro/install/share/lua/5.1/itorch/main.lua:48: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x00405330
```

**Comment by soumith** [comment]
@adamist521 looks like the previously failed itorch instance is still running and bound.
Close the terminal, open an new terminal.
Then type: killall luajit
then rerun "itorch notebook"

This is a one-time thing, because of the failure from earlier.

**Comment by adamist521** [comment]
Tried but didn't fix the error...

**Comment by soumith** [comment]
@adamist521 looks to be an issue on CentOS 6xx, I've reproduced, we're working on it.

**Comment by soumith** [comment]
@adamist521 fixed it via commit https://github.com/facebook/iTorch/commit/96e8a26a91a90d47583761a55b308364d391585c

thanks for the bug report and let us know if it fixes the issue. we will also be pushing an even more robust fix soon.

**Comment by adamist521** [comment]
Worked!! Thx!!

Looking forward for the update!

**Comment by rajeshnjr** [comment]
torch.load('cifar10-train.t7') after this command i am getting error as 
cannot open <> in mode r
stack traceback:

**Comment by rajeshnjr** [comment]
when i run the demo using itorch notebook it shows kernal dead
