### ISSUE TITLE
Jupyter Not Loading .ipynb - IPython 3.0.0

### ISSUE THREAD

**Issue by PrajitR** [facebook/iTorch#35]
`itorch` correctly gives me the console (which works). `itorch notebook` will correctly give me the file directory in the browser, showing me the various files. Creating a new itorch notebook also works correctly. However, loading an existing notebook does not work. It gives me the header (i.e. the top bar with all the options like `File` and `Cell`), but no actual cells load. This is on Ubuntu 14.04 with IPython 3.0.0.

However, if I downgrade to IPython 2.4.1, everything works. So this seems related to the other issues regarding IPython 3.0.0.

**Comment by soumith** [comment]
Sorry for the delay. I've fixed it via this commit: https://github.com/facebook/iTorch/commit/59be6bcaf64f737a2361158b3021923e1afde39f

All you have to do to get it working with IPython 3.0 is do:
```
luarocks install itorch
```

And then to start itorch in notebook mode:
```
itorch notebook
```
And then create a new iTorch notebook from dropdown menu.

starting `ipython notebook` wont work, starting `itorch notebook` will work.
I am looking to see how `ipython notebook` will also work in 3.0.
