### ISSUE TITLE
fix in gfx.lua

### ISSUE THREAD

**Issue by alisabri** [facebook/iTorch#36]
Hi,
In gfx.lua 'image' method, if user calls method with options then, 'input' field to 'toDisplay' function is nill

I think in gfx lua after line 18
    18  opts = opts or {input=img, padding=2}
change as :
    19  opts.input = img

Regards

**Comment by soumith** [comment]
fixed in trunk via commit: https://github.com/facebook/iTorch/commit/ec593dcf60b54ca401aa7bc255b95459155d9735
Thanks for the report
