### ISSUE TITLE
Plot() does not work out-of-the-box on OS X 10.10

### ISSUE THREAD

**Issue by alexbw** [facebook/iTorch#4]
Followed all install instructions, and all commands except for Plot() work right after install. Any advice?

**Comment by soumith** [comment]
@alexbw did you try:
```lua
Plot = require 'itorch.Plot'
```
I realized it was missing from the documentation and added it late yesterday.

**Comment by alexbw** [comment]
Perfect. Fixed it.

**Comment by adamist521** [comment]
`Plot = require 'itorch.Plot'` is still missing in demo notebook inside the repository!

**Comment by soumith** [comment]
@adamist521 good point, fixing it now.

**Comment by soumith** [comment]
fixed via https://github.com/facebook/iTorch/commit/7956068afcb9c66a19c5aa213b83aaf6060f5c48
