### ISSUE TITLE
iTorch fails to execute anything

### ISSUE THREAD

**Issue by Mdu7078** [facebook/iTorch#40]
I've installed iTorch on an Ubuntu 14.04 machine using the latest version of lzmq (0.4.2-1).  The iTorch server starts successfully, however any time that a command tries to execute, I get the following error in the console:

```
/usr/local/bin/luajit: /usr/local/share/lua/5.1/lzmq/ffi/api.lua:468: attempt to get length of local 'data' (a number value)
stack traceback:
        /usr/local/share/lua/5.1/lzmq/ffi/api.lua:468: in function 'zmq_send'
        /usr/local/share/lua/5.1/lzmq/ffi.lua:491: in function 'send'
        /usr/local/share/lua/5.1/lzmq/ffi.lua:525: in function 'send_all'
        /usr/local/share/lua/5.1/itorch/main.lua:150: in function </usr/local/share/lua/5.1/itorch/main.lua:140>
        /usr/local/share/lua/5.1/lzmq/ffi.lua:1129: in function 'poll'
        /usr/local/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
        /usr/local/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
        /usr/local/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
        /usr/local/share/lua/5.1/itorch/main.lua:341: in main chunk
        [C]: in function 'require'
        (command line):1: in main chunk
        [C]: at 0x004061d0
```

I'm not sure if this is a bug with lzmq or iTorch, but I'm not sure how to go about fixing this...

**Comment by soumith** [comment]
Hey @Mdu7078 , maybe you have a zeromq version installed that is not compatible with the lzmq bindings?

**Comment by Mdu7078** [comment]
@soumith I currently have zeromq version 4.0.5 installed which I assumed was compatible with lzmq since their github lists version 3.2/4.0 as supported.  Do you recommend that I downgrade to 3.2 instead?  On another note: the notebook application does report that it is using protocol v4.0 before it fails.

**Comment by soumith** [comment]
i'd like you to install the non-ffi version of the lzmq bindings. I've only ever tested with those. 
Install this: https://github.com/zeromq/lzmq/blob/master/rockspecs/lzmq-0.4.2-1.rockspec
You have this installed: https://github.com/zeromq/lzmq/blob/master/rockspecs/lzmq-ffi-0.4.2-1.rockspec

So:
```
luarocks remove lzmq-ffi
luarocks install lzmq
```

**Comment by Mdu7078** [comment]
That worked like a charm!

**Comment by VitoVan** [comment]
this really works! Thanks!
