### ISSUE TITLE
iTorch installation not finding ipython

### ISSUE THREAD

**Issue by kzachery** [facebook/iTorch#42]
Let me start by saying I am new to Torch, Lua and Ubuntu. I am running Torch7 under Ubuntu 14.04. I am trying to install iTorch, but am getting an error that ipython was not found. The path to my ipython installation is listed in my $PATH, so I am confused as to why the iTorch installation cannot find it. I followed the install steps stated at https://github.com/facebook/iTorch.git. I am running ipython 2.4.1 and python 2.7.6. I have searched numerous websites and tried their solutions, but have not yet been able to successfully install iTorch. Any suggestions or advice you could provide would be greatly appreciated!

Karen Zachery
kzachery@teledyne.com

**Comment by soumith** [comment]
Hey Karen,

Can you post the full log of the following commands:
```bash
git clone https://github.com/facebook/iTorch
cd iTorch
luarocks make
```

**Comment by kzachery** [comment]
kzachery@DELL:~/iTorch$ luarocks make
   ipy=$(which ipython)
   if [ -x "$ipy" ]
   then
     ipybase=$(ipython locate)
     rm -rf $ipybase/profile_torch
     ipython profile create torch
     echo 'c.KernelManager.kernel_cmd = ["/home/kzachery/torch/install/bin/itorch_launcher","{connection_file}"]' >>$ipybase/profile_torch/ipython_config.py
     echo "c.Session.key = b''" >>$ipybase/profile_torch/ipython_config.py
     echo "c.Session.keyfile = b''" >>$ipybase/profile_torch/ipython_config.py
     mkdir -p $ipybase/profile_torch/static/base/images
     mkdir -p $ipybase/kernels/itorch
     cat kernelspec/kernel.json | sed "s@LUA_BINDIR@/home/kzachery/torch/install/bin@" > $ipybase/kernels/itorch/kernel.json
     cp kernelspec/*.png $ipybase/kernels/itorch/
     cp ipynblogo.png $ipybase/profile_torch/static/base/images
     mkdir -p $ipybase/profile_torch/static/custom/
     cp custom.js $ipybase/profile_torch/static/custom/
     cp custom.css $ipybase/profile_torch/static/custom/
     cp itorch /home/kzachery/torch/install/bin/
     cp itorch_launcher /home/kzachery/torch/install/bin/
     cp -r ~/.ipython/profile_torch ~/.ipython/profile_itorch
     cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/kzachery/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1" && make
   else
     echo "Error: could not find ipython in PATH. Do you have it installed?"
   fi


[ProfileCreate] Generating default config file: u'/home/kzachery/.ipython/profile_torch/ipython_config.py'
[ProfileCreate] Generating default config file: u'/home/kzachery/.ipython/profile_torch/ipython_nbconvert_config.py'
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/kzachery/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kzachery/iTorch/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/main.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/Plot.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/completer.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/util.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/init.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/gfx.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/test.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/IOHandler.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/_env.lua
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh-0.7.0.min.js
-- Installing: /home/kzachery/torch/install/lib/luarocks/rocks/itorch/scm-1/lua/itorch/bokeh-0.7.0.min.css
Updating manifest for /home/kzachery/torch/install/lib/luarocks/rocks
itorch scm-1 is now built and installed in /home/kzachery/torch/install/ (license: BSD)

**Comment by soumith** [comment]
Karen,

It looks like itorch finds your ipython without any issues. Not sure why you thought it did not find your ipython.
The install-script is printed to screen, that might have confused you.

**Comment by kzachery** [comment]
Thanks for the reply. I guess I will have to read through the installation output again. I am still having issues with iTorch – must be some other library issue.

- knz
