### ISSUE TITLE
[OS X] Missing dependencies for itorch: luacrypto 

### ISSUE THREAD

**Issue by tokvokey** [facebook/iTorch#44]
Hey,

I get the following error when I type 'luarocks make ' in terminal:

Missing dependencies for itorch:
luacrypto 

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock... switching to 'build' mode

Error: Failed installing dependency: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock - Could not find expected file openssl/evp.h, or openssl/evp.h for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luacrypto OPENSSL_DIR=/usr/local

--------------------------------------

At first there were more dependencies missing but
luarocks install env
for example fixed it. 'luarocks install luacrypto' results in the following: 

Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock... switching to 'build' mode

Error: Could not find expected file openssl/evp.h, or openssl/evp.h for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luacrypto OPENSSL_DIR=/usr/local

---------------------------------------

I couldn't find a solution in the other issues and I cannot find the package in the torch rocks server(https://github.com/torch/rocks). I installed luarocks via Torch installation and iPython through anaconda. 

Any idea where I missteped?

**Comment by soumith** [comment]
on OSX 10.10, I get no error.
However, it seems like luacrypto cant find your OpenSSL.

Can you try something like:

luarocks install openssl OPENSSL_INCDIR='/usr/include/openssl/' 

you could also try to find evp.h on your system and give that directory as the path to the OPENSSL_INCDIR variable...

**Comment by tokvokey** [comment]
Okay I'm running OSX 10.10.3.

$ luarocks install openssl OPENSSL_INCDIR='/usr/include/openssl/'

gives:
Error: No results matching query were found.
---------------------------------------------

$ luarocks install luacrypto OPENSSL_INCDIR=/anaconda/pkgs/openssl-1.0.1k-1/include/openssl

gives:
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock... switching to 'build' mode

Error: Could not find expected file openssl/evp.h, or openssl/evp.h for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luacrypto OPENSSL_DIR=/usr/local

Which seem to be the same problem. Can my anaconda folder be located in the wrong location? 
Pretty new to these kind of installations.

**Comment by tokvokey** [comment]
It's now working. Thanks!

The output of 
itorch.image({image.lena(), image.lena(), image.lena()})
in iTorch notebook is just blank however:

Out[43]:

**Comment by soumith** [comment]
yaay! :)

what was your solution to install luacrypto? might be useful for others if you post here.

**Comment by tokvokey** [comment]
Ah! It had to do with openssl like you said. I think it worked because of this:
brew update
brew install openssl
brew link --force openssl

After that 
$ luarocks make 
installed iTorch without any problem. Thanks

**Comment by rewonc** [comment]
I had this problem when installing Torch today. The problem occurs when installing luacrypto, which depends on openssl.

Homebrew won't symlink the files into /usr/local as Mac OSX already provides some version of openssl. You should see an error message which includes the following line when you brew install openssl:

```
brew install openssl

=>  This formula is keg-only, so it was not symlinked into /usr/local.
      Generally there are no consequences of this for you. If you build your own software and it requires this formula, you'll need to add to your build variables:
      LDFLAGS:  -L/usr/local/opt/openssl/lib
      CPPFLAGS: -I/usr/local/opt/openssl/include
```

From here, you can either force link openssl to /usr/local like tokvokey suggests, but Homebrew recommends against doing as it might interfere with other software. What I did was simply do:

`luarocks install luacrypto OPENSSL_DIR=/usr/local/opt/openssl/`

I got OPENSSL_DIR from the homebrew error message. This cleared up the error for me.

**Comment by soumith** [comment]
that looks like a nicer solution @rewonc . I'm adding it to the README. Thanks.

**Comment by JinYoungChoi** [comment]
Hello, I am experiencing the same trouble on my mac.
I got the same error: 

Missing dependencies for itorch:
luacrypto 
uuid 
lzmq >= 0.4.2

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock... switching to 'build' mode

Error: Failed installing dependency: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock - Could not find expected file openssl/evp.h, or openssl/evp.h for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luacrypto OPENSSL_DIR=/usr/local

Thusly, I used the command @rewonc recommended, but still failed.(Same error as above appeared)
luarocks install luacrypto OPENSSL_DIR=/usr/local/opt/openssl/

Anyone can help me out?

**Comment by JinYoungChoi** [comment]
For more information, I checked out install.log file, and could see that having 209 lines. I am not sure torch has been installed successfully. I tried to access the shell using 'th' command but failed.

**Comment by mongoose54** [comment]
Similar issue here. Just following the instructions (http://torch.ch/docs/getting-started.html#installing-torch) and I get the following error when I ran `./install.sh`:

```
Missing dependencies for itorch:
lbase64 
luacrypto 
uuid 
lzmq >= 0.4.2

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lbase64-20120820-1.src.rock... switching to 'build' mode
Do not use 'module' as a build type. Use 'builtin' instead.
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -O2 -fPIC -I/Users/alexk/torch/install/include -c lbase64.c -o lbase64.o
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -bundle -undefined dynamic_lookup -all_load -o base64.so -L/Users/alexk/torch/install/lib lbase64.o
Updating manifest for /Users/alexk/torch/install/lib/luarocks/rocks
lbase64 20120820-1 is now built and installed in /Users/alexk/torch/install/ (license: Public domain)

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock... switching to 'build' mode

Error: Failed installing dependency: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luacrypto-0.3.2-1.src.rock - Could not find expected file openssl/evp.h, or openssl/evp.h for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luacrypto OPENSSL_DIR=/usr/local

```

Any help? Thanks!

**Comment by alexbarros** [comment]
@mongoose54tive I had the same issue, and I was able to solve this installing the luarocks (apt-get install luarocks) and installing the missing dependencies manualy. 
`
luarocks install lbase64
luarocks install luacrypto 
luarocks install uuid 
luarocks install lzmq
`
luacrypto requires libssl-dev package, that can be installed using:
`apt-get install libssl-dev`

**Comment by rawberg** [comment]
For OSX with homebrew this worked (be sure to lookup and replace the version)
`luarocks-5.1 install luacrypto OPENSSL_INCDIR=/usr/local/Cellar/openssl/1.0.2h_1/include`

**Comment by rawberg** [comment]
For OSX with homebrew this worked (be sure to lookup and replace the version)
luarocks-5.1 install luacrypto OPENSSL_INCDIR=/usr/local/Cellar/openssl/1.0.2h_1/include

**Comment by Ashutosh1995** [comment]
Can I install openssl using pip as I don't have the sudo access

**Comment by bfontaine** [comment]
> For OSX with homebrew this worked (be sure to lookup and replace the version)
> `luarocks-5.1 install luacrypto OPENSSL_INCDIR=/usr/local/Cellar/openssl/1.0.2h_1/include`

I’m a bit late to the party but you should use `/usr/local/opt/openssl/include` instead; it’ll always point to the latest version. `brew --prefix <formula>` gives you that path:

```
luarocks-5.1 install luacrypto OPENSSL_INCDIR=$(brew --prefix openssl)/include
```
