### ISSUE TITLE
iTorch notebook kernel will not start. 

### ISSUE THREAD

**Issue by physicsman** [facebook/iTorch#45]
[I 16:39:27.634 NotebookApp] KernelRestarter: restarting kernel (1/5)
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
/Users/jmcdonald/torch/install/bin/luajit: error loading module 'lzmq.timer' from file '/usr/local/lib/lua/5.1/lzmq/timer.so':
	dlopen(/usr/local/lib/lua/5.1/lzmq/timer.so, 6): Symbol not found: _luaL_setfuncs
  Referenced from: /usr/local/lib/lua/5.1/lzmq/timer.so
  Expected in: dynamic lookup

stack traceback:
	[C]: at 0x010f6d1e80
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lzmq/impl/loop.lua:15: in function </usr/local/share/lua/5.1/lzmq/impl/loop.lua:11>
	[C]: in function 'require'
	/usr/local/share/lua/5.1/itorch/IOHandler.lua:13: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x010f6a0320

**Comment by ibmua** [comment]
I'm experiencing same sort of issues. There's a possibility that this is due to lack of support for a newer version of ipython by itorch.
```
$ itorch
/home/ihor/anaconda/lib/python2.7/site-packages/IPython/kernel/manager.py:95: UserWarning: Setting kernel_cmd is deprecated, use kernel_spec to start different kernels.
  warnings.warn("Setting kernel_cmd is deprecated, use kernel_spec to "
qlua: error loading module 'lzmq' from file '/home/ihor/torch/install/lib/lua/5.1/lzmq.so':
	/home/ihor/torch/install/lib/lua/5.1/lzmq.so: undefined symbol: zmq_proxy_steerable
stack traceback:
	[C]: at 0x7f66bfcb4970
	[C]: at 0x7f66bfa89fe0
	[C]: in function 'require'
	/home/ihor/torch/install/share/lua/5.1/itorch/main.lua:11: in main chunk
	[C]: in function 'require'
	[string "arg={'/home/ihor/.ipython/profile_torch/secur..."]:1: in main chunk
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
qlua: error loading module 'lzmq' from file '/home/ihor/torch/install/lib/lua/5.1/lzmq.so':
	/home/ihor/torch/install/lib/lua/5.1/lzmq.so: undefined symbol: zmq_proxy_steerable
stack traceback:
	[C]: at 0x7ff0c3bfc970
	[C]: at 0x7ff0c39d1fe0
	[C]: in function 'require'
	/home/ihor/torch/install/share/lua/5.1/itorch/IOHandler.lua:12: in main chunk
	[C]: in function 'require'
	[string "arg={'/home/ihor/.ipython/profile_torch/secur..."]:1: in main chunk
IPython Console 3.0.0

IPython profile: torch
```

**Comment by physicsman** [comment]
I think its an issue with linking and different versions of Lua but Im not really sure. Im new to this

**Comment by physicsman** [comment]
Check: https://github.com/facebook/iTorch/issues/46#issuecomment-111312628
