### ISSUE TITLE
iTorch kernel crashes. 

### ISSUE THREAD

**Issue by physicsman** [facebook/iTorch#46]
Having trouble with 'lzmq' I think. Tried a lot of reinstalling a such. (Mac OSX Yosemite V10.10.3)

[I 14:41:38.538 NotebookApp] Kernel started: 8d658bc6-e9bc-4db2-beb0-db3335488f4c
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
/Users/jmcdonald/torch/install/bin/luajit: error loading module 'lzmq' from file '/usr/local/lib/lua/5.1/lzmq.so':
	dlopen(/usr/local/lib/lua/5.1/lzmq.so, 6): Symbol not found: _luaL_setfuncs
  Referenced from: /usr/local/lib/lua/5.1/lzmq.so
  Expected in: dynamic lookup

stack traceback:
	[C]: at 0x010225ae80
	[C]: in function 'require'
	/usr/local/share/lua/5.1/itorch/IOHandler.lua:12: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x0102229320

**Comment by soumith** [comment]
this is always problematic if you have two torch installs. you are never sure what library you linked against.

I strongly suggest that you remove the lua/torch version that seems to be installed in /usr/local/

**Comment by physicsman** [comment]
I can remove the the /usr/local/lib/lua but when I run the torch install it just puts it right back.

**Comment by soumith** [comment]
hmmm, that makes no sense. How are you installing torch? Are you using instructions from the website? torch.ch/docs/getting-started.html#_

**Comment by physicsman** [comment]
essentially I think, https://github.com/torch/ezinstall

**Comment by physicsman** [comment]
if I run the install script suggested on torch.ch after removing /usr/local/lib/lua it just installs a ~/torch/install/lib/lua and gives the same error just in the new directory

**Comment by soumith** [comment]
once you've done a global install (because you used instructions from  https://github.com/torch/ezinstall ), lots of additional files get installed that might just conflict with the local install.

Use this script to clean your global install, then reinstall it with instructions from torch.ch:

https://github.com/torch/ezinstall/blob/master/clean-old.sh

**Comment by physicsman** [comment]
Same story: 

[I 17:18:10.580 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 17:18:10.627 NotebookApp] Serving notebooks from local directory: /Users/jmcdonald/work
[I 17:18:10.627 NotebookApp] 0 active kernels 
[I 17:18:10.627 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 17:18:10.627 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 17:18:16.219 NotebookApp] Creating new notebook in 
[I 17:18:17.024 NotebookApp] Kernel started: 376c5d6b-03e5-4c14-bd05-1c5e5386fbbf
Torch 7.0  Copyright (C) 2001-2011 Idiap, NEC Labs, NYU
qlua: error loading module 'lzmq' from file '/Users/jmcdonald/torch/install/lib/lua/5.1/lzmq.so':
	dlopen(/Users/jmcdonald/torch/install/lib/lua/5.1/lzmq.so, 6): Symbol not found: _zmq_has
  Referenced from: /Users/jmcdonald/torch/install/lib/lua/5.1/lzmq.so
  Expected in: dynamic lookup

stack traceback:
	[C]: at 0x010bef11d0
	[C]: at 0x010bf4c4b0
	[C]: in function 'require'
	...cdonald/torch/install/share/lua/5.1/itorch/IOHandler.lua:12: in main chunk
	[C]: in function 'require'
	[string "arg={'/Users/jmcdonald/.ipython/profile_defau..."]:1: in main chunk

**Comment by soumith** [comment]
now you seem to have two versions of ZeroMQ installed on your machine....

**Comment by soumith** [comment]
it's a different error message if you notice.

**Comment by physicsman** [comment]
I see. I now have a working install

I did a bunch of stuff and at this point Im too bonked to figure out how to explain or abbreviate the steps I took so here is a bash history vomit:
'brew uninstall zmq'
'cd ~/torch; ./install.sh'
'curl -s https://raw.githubusercontent.com/torch/ezinstall/master/clean-old.sh | bash'
'curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash'
'rm /usr/local/include/zmq.h'
'curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash'
'rm -rf ~/torch/'
'git clone https://github.com/torch/distro.git ~/torch --recursive'
'cd ~/torch; ./install.sh'
'source ~/.profile'
'brew link --overwrite --dry-run zeromq'
'brew link --overwrite zeromq'
'luarocks install lzmq'
'rm -rf ~/torch/'
'curl -s https://raw.githubusercontent.com/torch/ezinstall/master/clean-old.sh | bash'
'curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash'
'git clone https://github.com/torch/distro.git ~/torch --recursive'
'cd ~/torch; ./install.sh'
'source ~/.profile'

**Comment by soumith** [comment]
Sorry about this whole mess. I added a big warning to the readme of ezinstall so that one does not install torch using install-all by mistake and instead goes to the website.

https://github.com/torch/ezinstall/commit/7b8ab167f7c2650ce438d64a088c7df80dfa13a9

**Comment by physicsman** [comment]
I think I might have messed it up by installing dependancies with 'brew'

**Comment by physicsman** [comment]
Thanks for sticking around to help!
