### ISSUE TITLE
itorch._iopub socket not set

### ISSUE THREAD

**Issue by tonyyang1993** [facebook/iTorch#63]
After terminaled in server through `ssh -X` to, tried 
```
th> require 'itorch';
th> itorch.image({image.lena(), image.lena(), image.lena()})
```
Got following error
```
/root/torch/install/share/lua/5.1/itorch/gfx.lua:12: itorch._iopub socket not set
stack traceback:
	[C]: in function 'assert'
	/root/torch/install/share/lua/5.1/itorch/gfx.lua:12: in function 'image'
	[string "_RESULT={ itorch.image({image.lena(), image.l..."]:1: in main chunk
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670
```

Same error was reported: https://groups.google.com/forum/#!topic/torch7/EFabrnkyTQE

Does anyone know how to display images through `ssh`? Based on my past experience of python and MATLAB, `ssh -X` should work...

Any comments are welcomed.

**Comment by marvin521** [comment]
I have a similar problem here, have you solved the problem？

**Comment by jaiabhayk** [comment]
Is it solved ? i am facing same problem with OSX yoshemite.

**Comment by soumith** [comment]
itorch has to be started with it's own console. if you require itorch in regular th, you get this error.

**Comment by soumith** [comment]
if you look at the docs, you'll have to start it with "itorch" or "itorch notebook"

**Comment by jaiabhayk** [comment]
Thanks.

**Comment by tylerlindell** [comment]
in the tutorial here: https://github.com/soumith/cvpr2015/blob/master/Deep%20Learning%20with%20Torch.ipynb

It is showing what looks like the use of itorch.image() in regular th, is that the wrong way to do it? I am getting this same error as noted in OP post. Thank you!

**Comment by 1byxero** [comment]
How to use itorch in th7

**Comment by 1byxero** [comment]
I found out how to get this working.
After setting up the environment dependencies

type 
itorch notebook
this will open a new notebook in the browser
open new terminal in the notebook 
and work in that notebook terminal.

**Comment by CuriousCat-7** [comment]
I think the better way may be using 'image' module instead of itorch.
require 'image'
image.save('yourImageName.png', tensor)

and then open it.
This is the best way I've found when working via ssh.
