### ISSUE TITLE
iTorch histogram demo fails

### ISSUE THREAD

**Issue by seninp** [facebook/iTorch#69]
when running the demo

    -- histogram
    x=torch.randn(10000)
    lx = torch.log(x):add(1)
    plot = Plot():histogram(x):histogram(lx):title('Histogram of a gaussian draw'):draw()

it throws an exception:

    bad argument #2 to '?' (end range should be greater than start range at /tmp/luarocks_torch-scm-1-4053/torch7/lib/TH/generic/THTensorMath.c:2100)
    stack traceback:
	[C]: at 0x7f12b92107c0
	[C]: in function 'linspace'
	/usr/local/share/lua/5.1/itorch/Plot.lua:215: in function 'histogram'
	[string "..."]:5: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/itorch/main.lua:179: in function </usr/local/share/lua/5.1/itorch/main.lua:143>
	/usr/local/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	/usr/local/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	/usr/local/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	/usr/local/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/usr/local/share/lua/5.1/itorch/main.lua:350: in main chunk
	[C]: in function 'require'
	[string "arg={'/home/psenin/.ipython/profile_default/s..."]:1: in main chunk

**Comment by soumith** [comment]
hey pavel, that is because lx here has nans

**Comment by soumith** [comment]
you can verify simply by:
print(lx:min(), lx:max())

or even 
print(lx:ne(lx):sum()) -- number of nans present

**Comment by seninp** [comment]
i see that, it can be something like `lx = torch.log(torch.abs(x))`, or was that left for the user exercise :)? thanks for the quick response!

**Comment by soumith** [comment]
pushed a patch that warns the users about nans.
