### ISSUE TITLE
Install iTorch on MAC

### ISSUE THREAD

**Issue by kemaswill** [facebook/iTorch#70]
Does any one successfully installed the iTorch on MAC? I got the ERROR: "Error: Could not satisfy dependency: lzmq >= 0.4.2" when run the `luarocks make` commands. I just follow the install steps in the document:

brew install zeromq
brew install openssl
luarocks install luacrypto OPENSSL_DIR=/usr/local/opt/openssl/
git clone https://github.com/facebook/iTorch.git
cd iTorch
luarocks make  

Could anyone help? Thanks a lot.

**Comment by soumith** [comment]
@kemaswill a full log of your install will help.
