### ISSUE TITLE
how to start using iTorch?

### ISSUE THREAD

**Issue by stianSjoli** [facebook/iTorch#77]
I have successfully installed iTorch, and I get the tree hierarchy display at localhost:8888 when I write torch notebook. however, have you mentioned how to start your own interactive session? the read-file says exactly what is mentioned on the github page.

**Comment by stianSjoli** [comment]
I discovered the "new" button in the right corner so my problem is gone. Maybe its worth a small comment about it in your readme-file? (I dont think it has that)

**Comment by soumith** [comment]
thanks for the feedback, added a small note in the README
