### ISSUE TITLE
iTorch doesn't start a torch session

### ISSUE THREAD

**Issue by metatl** [facebook/iTorch#80]
I'm on a Mac 10.8, latest Xcode, ipython 4, python 2.7.*. Python, ipython are installed with conda 

When I run 'itorch notebook --debug' here is the log. No interactive torch session is started. In the 'new' tab of Jupyter I can only start a notebook kernel, but that's python, not torch. Anyone could help with this?

> ~ foouser$ itorch notebook --debug
[D IP address NotebookApp] Config changed:
[D IP address NotebookApp] {'NotebookApp': {'log_level': 10}, 'MappingKernelManager': {'default_kernel_name': u'itorch'}}
[D IP address NotebookApp] Searching [u'/Users/foouser', '/Users/foouser/.jupyter', '/Users/foouser/anaconda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D IP address2 NotebookApp] Attempting to load config file jupyter_config.py in path /etc/jupyter
[D IP address2 NotebookApp] Attempting to load config file jupyter_config.json in path /etc/jupyter
[D IP address2 NotebookApp] Attempting to load config file jupyter_config.py in path /usr/local/etc/jupyter
[D IP address2 NotebookApp] Attempting to load config file jupyter_config.json in path /usr/local/etc/jupyter
[D IP address2 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/foouser/anaconda/etc/jupyter
[D IP address2 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/foouser/anaconda/etc/jupyter
[D IP address2 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/foouser/.jupyter
[D IP address3 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/foouser/.jupyter
[D IP address3 NotebookApp] Attempting to load config file jupyter_config.py in path /Users/foouser
[D IP address3 NotebookApp] Attempting to load config file jupyter_config.json in path /Users/foouser
[D IP address3 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /etc/jupyter
[D IP address3 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /etc/jupyter
[D IP address3 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /usr/local/etc/jupyter
[D IP address3 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /usr/local/etc/jupyter
[D IP address4 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/foouser/anaconda/etc/jupyter
[D IP address4 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/foouser/anaconda/etc/jupyter
[D IP address4 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/foouser/.jupyter
[D IP address4 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/foouser/.jupyter
[D IP address4 NotebookApp] Attempting to load config file jupyter_notebook_config.py in path /Users/foouser
[D IP address4 NotebookApp] Attempting to load config file jupyter_notebook_config.json in path /Users/foouser
[I IP address5 NotebookApp] Serving notebooks from local directory: /Users/foouser
[I IP address5 NotebookApp] 0 active kernels 
[I IP address5 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I IP address5 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 14:11:16.158 NotebookApp] 200 GET /api/sessions?_=1445969410612 (::1) 2.77ms
[D 14:11:16.160 NotebookApp] 200 GET /api/terminals?_=1445969410613 (::1) 0.64ms
[D 14:11:16.261 NotebookApp] 200 GET /api/contents?type=directory&_=1445969410614 (::1) 31.09ms
[D 14:11:16.263 NotebookApp] Using contents: services/contents
[D 14:11:16.314 NotebookApp] 200 GET /tree (::1) 52.10ms
[D 14:11:16.417 NotebookApp] 304 GET /custom/custom.css (::1) 0.93ms
[D 14:11:16.590 NotebookApp] 200 GET /static/services/contents.js?v=20151027141115 (::1) 1.01ms
[D 14:11:16.594 NotebookApp] 200 GET /custom/custom.js?v=20151027141115 (::1) 1.05ms
[D 14:11:16.616 NotebookApp] 200 GET /api/config/tree?_=1445969476535 (::1) 0.80ms
[D 14:11:16.618 NotebookApp] 200 GET /api/config/common?_=1445969476536 (::1) 0.62ms
[D 14:11:16.626 NotebookApp] 200 GET /api/terminals?_=1445969476537 (::1) 1.05ms
[D 14:11:16.630 NotebookApp] Native kernel (python2) available from /Users/foouser/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 14:11:16.631 NotebookApp] Native kernel (python2) available from /Users/foouser/anaconda/lib/python2.7/site-packages/ipykernel/resources
[D 14:11:16.633 NotebookApp] 304 GET /api/kernelspecs (::1) 4.71ms
[D 14:11:16.635 NotebookApp] 200 GET /api/terminals?_=1445969476539 (::1) 1.07ms
[D 14:11:16.637 NotebookApp] 200 GET /api/sessions?_=1445969476538 (::1) 0.92ms
[D 14:11:16.674 NotebookApp] 200 GET /api/contents?type=directory&_=1445969476540 (::1) 19.31ms

**Comment by metatl** [comment]
Issue solved.

**Comment by soumith** [comment]
what was the issue?

**Comment by metatl** [comment]
@soumith 
I don't know exactly. I reinstalled everything and it just worked.
