### ISSUE TITLE
iTorch installation

### ISSUE THREAD

**Issue by np25** [facebook/iTorch#83]
Even after installing itorch, when I run the command "itorch notebook", the command is not recognized."[string "itorch notebook"]:1: '=' expected near 'notebook'"
This is the same message when itorch was not installed.
Is there something wrong with the installation?

**Comment by np25** [comment]
I had also tried the command to install itorch using " luarocks install itorch".
However, I got the following error:

Installing https://raw.githubusercontent.com/torch/rocks/master/itorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/itorch-scm-1.rockspec... switching to 'build' mode

Missing dependencies for itorch:
lzmq >= 0.4.2

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lzmq-0.4.3-1.src.rock... switching to 'build' mode

Error: Failed installing dependency: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lzmq-0.4.3-1.src.rock - Could not find expected file zmq.h, or zmq.h for ZMQ -- you may have to install ZMQ in your system and/or pass ZMQ_DIR or ZMQ_INCDIR to the luarocks command. Example: luarocks install lzmq ZMQ_DIR=/usr/local

Please let me know how do I proceed

**Comment by reckdk** [comment]
I think you need to install ZMQ(ZeroMQ) and then install Pyzmq to satisfy this dependencies for itorch. Both can be find on their offical websites.
