### ISSUE TITLE
iTorch Not Exiting on Ubuntu 14.04.2

### ISSUE THREAD

**Issue by tralpha** [facebook/iTorch#88]
I successfully installed iTorch on Ubuntu 14.04.2 (IPython 4.0.1) running on ec2 server, but however I can't exit itorch console after I run it (using itorch command)

The program just hangs. Nothing returns, not even an error log (wished there was one so I could understand what's happening)

The only way I exit itorch console is by killing the screen where it runs.

Can anyone help? I included an image of what's happening below
<img width="484" alt="screen shot 2015-12-24 at 9 16 48 am" src="https://cloud.githubusercontent.com/assets/8296892/11987800/a97c0d20-aa20-11e5-83ea-9810404730aa.png">

**Comment by soumith** [comment]
@tralpha To exit, you can either use Ctrl + D, or Ctrl + \
