### ISSUE TITLE
No syntax highlighting in notebook 

### ISSUE THREAD

**Issue by malmaud** [facebook/iTorch#9]
About the half the time I load a torch notebook, I get syntax highlighting; the other half I do not (all text in code cells is just in black). 
This is in chrome 39.0.2171.99 on OS X 10.10.1.

For reference, syntax highlighting with the normal IPython profile (eg from using ``ipython notebook``) reliably gives syntax highlighting.

**Comment by soumith** [comment]
we actually dont use anything different for syntax highlighting than what ipython ships with (CodeMirror). We give a language hint: https://github.com/facebook/iTorch/blob/master/custom.js#L8
and ipython takes care of the rest.

**Comment by malmaud** [comment]
In that case, this is probably the same race condition affecting us at IJulia: https://github.com/JuliaLang/IJulia.jl/issues/168.

**Comment by hamannju** [comment]
I had the same problem. Syntax highlighting appeared when manually changed the "Cell Type" on the top of a notebook to "Code".

**Comment by andreaferretti** [comment]
Having the same issue. For some reason, it only happend in Firefox, and only for certain notebooks

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by zmughal** [comment]
This may have been fixed in IPython 3.2. See the issue at <https://github.com/EntropyOrg/p5-Devel-IPerl/issues/40> for more details.

**Comment by soumith** [comment]
nice. thanks for letting me know @zmughal
