### ISSUE TITLE
itorch.image(i) is showing error

### ISSUE THREAD

**Issue by aditya-shekhar** [facebook/iTorch#90]
i=image.lena()
This step is working , as when i print the matrix i, its printing the whole matrix.But , when i run this command:
Itorch.image(i)
Its showing this error:-
[string "_RESULT={itorch.image({image.lena()})}"]:1: attempt to index global 'itorch' (a nil value)
stack traceback:
	[string "_RESULT={itorch.image({image.lena()})}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/aditya/torch/install/share/lua/5.1/trepl/init.lua:650: in function 'repl'
	...itya/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670

**Comment by soumith** [comment]
@aditya-shekhar you need to run itorch. You are trying to run itorch display commands in the regular "th" repl.

https://github.com/facebook/iTorch#how-itorch-works

**Comment by aditya-shekhar** [comment]
image.display is also not working, when i run this command in torch
