### ISSUE TITLE
Errors with jupyter 4.1.0

### ISSUE THREAD

**Issue by alexbw** [facebook/iTorch#97]
There's apparently some issues cropped up with jupyter 4.1.0 for lots of folks running custom kernels. FYI, if you get an error that looks like:

```
lua: /Users/Alex/anaconda/share/lua/5.1/itorch/main.lua:319: Cannot find appropriate message handler for is_complete_request
stack traceback:
	[C]: in function 'assert'
	/Users/Alex/anaconda/share/lua/5.1/itorch/main.lua:319: in function </Users/Alex/anaconda/share/lua/5.1/itorch/main.lua:317>
	/Users/Alex/anaconda/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	/Users/Alex/anaconda/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	/Users/Alex/anaconda/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	/Users/Alex/anaconda/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/Users/Alex/anaconda/share/lua/5.1/itorch/main.lua:350: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x0100001570
```

Then try running iTorch like so:

```
jupyter console --kernel=itorch --ZMQTerminalInteractiveShell.use_kernel_is_complete=False
```

Although I'm still having a weird issue where I have to hit enter twice to run a command. Anybody seeing the same thing?

**Comment by soumith** [comment]
cool, checking now

**Comment by soumith** [comment]
hmmm, not seeing any side-effects.

The version of the notebook server is 4.1.0 and is running on:
Python 2.7.11 |Anaconda 2.1.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)]

What OS? I am using OSX 10.11.2

**Comment by soumith** [comment]
i'm going to try your command above, just tried it so far with regular itorch.

**Comment by soumith** [comment]
ohh, reproduced the issue in itorch console.

**Comment by alexbw** [comment]
jupyter                   1.0.0                    py27_1    defaults
jupyter_client            4.1.1                    py27_0    defaults
jupyter_console           4.1.0                    py27_0    defaults
jupyter_core              4.0.6                    py27_0    defaults
ipython-notebook          4.0.4                    py27_0    defaults
notebook                  4.1.0                    py27_0    defaults
ipython                   4.0.3                    py27_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_0    defaults
ipython-qtconsole         4.0.1                    py27_0    defaults
ipython_genutils          0.1.0                    py27_0    defaults

**Comment by alexbw** [comment]
Ah, yeah, no problems with the notebook, just the console.

**Comment by soumith** [comment]
fixed via https://github.com/facebook/iTorch/commit/d7c8a9a86ca87dbb76a555dcbbb50a1862914543

**Comment by alexbw** [comment]
Are you able to see the "press enter twice" bug?

**Comment by soumith** [comment]
ohh, right i forgot to look into that while i was fixing this. looking now.

**Comment by alexbw** [comment]
No, you fixed it.

**Comment by soumith** [comment]
oh ok cool :)
the double-enter is still present if you use the  --ZMQTerminalInteractiveShell.use_kernel_is_complete=False flag, but i'm not going to hunt for a workaround for that.
